### ISSUE TITLE
phonetisaurus_apply was renamed 

### ISSUE THREAD

**Issue by smolendawid** [danijel3/ClarinStudioKaldi#2]
phonetisaurus_apply, that is used in _clarin_prepare_dict.sh_, was renamed into phonetisaurus-apply on 29.08.2017

https://github.com/AdolfVonKleist/Phonetisaurus/commit/46bb7b7d8a8c57fedaefe2ea18f1d4c79cc24890

**Comment by danijel3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [phonetisaurus_apply was renamed](https://trello.com/c/Yo9Q3s5v/13-phonetisaurusapply-was-renamed)
