### ISSUE TITLE
Getting rid of SRILM?

### ISSUE THREAD

**Issue by smolendawid** [danijel3/ClarinStudioKaldi#3]
I think that some of the scripts can run without SRILM tool. However, in _local_clarin/clarin_pl_data_prep.sh_ there is a _ngram_ command, that comes from SRILM, as far as I understand (but it does not perform any advanced task)

The corpus is said to be created for commercial and non-commercial use. Maybe it would be nice to allow the scripts to run with only open-licence tools too? The SRILM in this place is probably the only one limitation.

**Comment by danijel3** [comment]
That command is used to extract the vocabulary from the language model. I'll have a look if there is any other neat utility to do that. Otherwise, it shouldn't be difficult to extract words from an ARPA model in a script. I'd just prefer to avoid introducing my own utilities if I can....

**Comment by danijel3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Getting rid of SRILM?](https://trello.com/c/Ya0F2YzK/12-getting-rid-of-srilm)
