### ISSUE TITLE
Performing speech recognition

### ISSUE THREAD

**Issue by TomGledhill** [danijel3/ClarinStudioKaldi#7]
Hello @danijel3 ! Thanks for the great project!
I want to try to perform speech recognition for polish. How can I get transcriptions having only audio recordings of speech?
Thanks!

**Comment by danijel3** [comment]
We have a website https://mowa.clarin-pl.eu with a service that you can use. If you know Docker, you can also use my images described here: https://github.com/danijel3/SpeechToolsWorkers/tree/master/speech_tools

There are also other free (e.g. WebMaus) and non-free (e.g. Google Speech) services that provide transcriptions of Polish.
