### ISSUE TITLE
Compatible Kaldi version

### ISSUE THREAD

**Issue by TomekZet** [danijel3/ClarinStudioKaldi#8]
Which version of Kaldi should currently be used with ClarinStudio setup?
Is it still the one "pulled from the github on Aug, 11. 2017"?

**Comment by danijel3** [comment]
I've used the script with the most recent versions of Kaldi and didn't run into any issues. If you have problems, let me know and I'll gladly fix them.

**Comment by TomekZet** [comment]
Thank you. I've just tried and it looks that it works with the latest version for me too.
What didn't work for me was the version from Aug, 11. 2017 - with this version the training failed on:
```
+ steps/train_mono.sh --nj 40 data/train data/lang_nosp exp/mono0
steps/train_mono.sh --nj 40 data/train data/lang_nosp exp/mono0
steps/train_mono.sh: Initializing monophone system.
steps/train_mono.sh: Compiling training graphs
steps/train_mono.sh: Aligning data equally (pass 0)
steps/train_mono.sh: Pass 1
steps/train_mono.sh: Aligning data
run.pl: 24 / 40 failed, log is in exp/mono0/log/align.1.*.log
```

Probably it would be a good idea to remove this mention about Kaldi version from README

**Comment by danijel3** [comment]
Ok.
